# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            davidw
url:              http://david-westreicher.github.io

author:
  name:           'David Westreicher'

paginate:         1

# Custom vars
version:          2.0.0

github:           https://github.com/david-westreicher/
twitter:          https://twitter.com/daviddefdef
