# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            davidw
tagline:          'A personal page'
description:      "reach me on <a href=\"https://twitter.com/daviddefdef\">twitter</a> or <a href=\"https://github.com/david-westreicher\">github</a>"
url:              http://david-westreicher.github.io/

author:
  name:           'David Westreicher'
  url:            https://twitter.com/daviddefdef

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/david-westreicher/
